# File: service-prometheus.yaml
# Descrizione: Service NodePort per Prometheus, permette di accedere all’interfaccia web da fuori Minikube.

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
