# File: configmap-otel-with-external-export.yaml
# Descrizione: ConfigMap OTEL esteso per esportare metriche verso SigNoz e Kafka
# Questo file NON sostituisce quello originale, è una versione estesa

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config-extended
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      # Receiver per raccogliere metriche da cAdvisor e kubelet
      prometheus:
        config:
          scrape_configs:
            # cAdvisor metrics da tutti i nodi
            - job_name: 'cadvisor'
              metrics_path: /metrics/cadvisor
              scheme: https
              kubernetes_sd_configs:
                - role: node
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: node
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  target_label: instance

            # kubelet metrics
            - job_name: 'kubelet'
              metrics_path: /metrics
              scheme: https
              kubernetes_sd_configs:
                - role: node
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: node

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
      # Aggiungi attributi custom per identificare la sorgente
      attributes:
        actions:
          - key: telemetry.source
            value: "kubernetes-cluster"
            action: insert
          - key: environment
            value: "production"
            action: insert

    exporters:
      # 1. Prometheus (locale) - Espone su porta 9464
      prometheus:
        endpoint: "0.0.0.0:9464"
        namespace: "otel"
        const_labels:
          source: "kubernetes"
          collector: "otel"
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true

      # 2. OTLP/gRPC per Kafka (porta 4317)
      otlp/grpc:
        endpoint: "0.0.0.0:4317"
        tls:
          insecure: true
        headers:
          kafka-topic: "kubernetes-metrics"
          cluster-name: "production-cluster"

      # 3. OTLP/HTTP per SigNoz (porta 4318)
      otlp/http:
        endpoint: "0.0.0.0:4318"
        tls:
          insecure: true
        headers:
          signoz-tenant: "default"
          cluster-name: "production-cluster"

      # 4. Logging per debugging
      logging:
        loglevel: info
        sampling_initial: 1
        sampling_thereafter: 1

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [attributes, memory_limiter, batch]
          exporters: [prometheus, otlp/grpc, otlp/http, logging] 