# File: configmap-otel-kafka.yaml
# Descrizione: ConfigMap OTEL per raccogliere metriche e esportarle direttamente su Kafka e Prometheus locale

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config-kafka
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      # Receiver per raccogliere metriche da cAdvisor e kubelet
      prometheus:
        config:
          scrape_configs:
            # cAdvisor metrics da tutti i nodi
            - job_name: 'cadvisor'
              metrics_path: /metrics/cadvisor
              scheme: https
              kubernetes_sd_configs:
                - role: node
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: node
                - source_labels: [__meta_kubernetes_node_address_InternalIP]
                  target_label: instance

            # kubelet metrics
            - job_name: 'kubelet'
              metrics_path: /metrics
              scheme: https
              kubernetes_sd_configs:
                - role: node
              tls_config:
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_name]
                  target_label: node

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
      # Aggiungi attributi custom per identificare la sorgente
      attributes:
        actions:
          - key: telemetry.source
            value: "kubernetes-cluster"
            action: insert
          - key: environment
            value: "production"
            action: insert
          - key: cluster.name
            value: "minikube"
            action: insert
          - key: data.type
            value: "metrics"
            action: insert

    exporters:
      # 1. Prometheus (locale) - Espone su porta 9464
      prometheus:
        endpoint: "0.0.0.0:9464"
        namespace: "otel"
        const_labels:
          source: "kubernetes"
          collector: "otel"
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true

      # 2. Kafka - Esporta metriche direttamente su Kafka
      kafka:
        brokers: 
          - "kafka:9092"
        topic: "otel-metrics"
        encoding: "otlp_proto"
        # Configurazione per retry
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

      # 3. Debug per debugging
      debug:
        verbosity: normal

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [attributes, memory_limiter, batch]
          exporters: [prometheus, kafka, debug] 