# File: deployment-otel.yaml
# Descrizione: Deployment OpenTelemetry Collector per raccogliere metriche da cAdvisor e standardizzarle per Prometheus

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.103.0
          args:
            - "--config=/etc/otel/config.yaml"
          ports:
            - containerPort: 9464
              name: metrics
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464 