# File: rbac-otel.yaml
# Descrizione: RBAC per l'OpenTelemetry Collector per accedere alle metriche del cluster

apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-otel-collector
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-otel-collector
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/metrics", "pods/logs"]
    verbs: ["get"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/metrics/resource/v1alpha1"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infra-otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infra-otel-collector
subjects:
  - kind: ServiceAccount
    name: infra-otel-collector
    namespace: monitoring 