# File: service-otel-with-external-export.yaml
# Descrizione: Service OTEL esteso con porte OTLP per export esterno
# Questo file NON sostituisce quello originale, è una versione estesa

apiVersion: v1
kind: Service
metadata:
  name: otel-collector-extended
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP 