# File: service-kafka-proxy.yaml
# Descrizione: Servizio proxy per Kafka nel namespace monitoring

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: monitoring
spec:
  type: ExternalName
  externalName: kafka.kafka.svc.cluster.local
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka 